version: '3.8'

services:
 
  backend:
    image: cadastro-desenvolvedores-backend
    container_name: backend
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
    depends_on:
      - mysql
    networks:
      - app_network
      
  frontend:
    build: .
    image: cadastro-desenvolvedores-frontend
    container_name: frontend
    restart: always
    ports:
      - "90:80"
    volumes:
      - ./dist:/usr/share/nginx/html

  mysql:
    image: mysql:8
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cadastro-desenvolvedores
      MYSQL_USER: vitor
      MYSQL_PASSWORD: senha1
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

volumes:
  mysql_data:
    driver: local

networks:
  app_network:
    driver: bridge